### ISSUE TITLE
NullPointerException nel caso di invocazione di lexicon/data/lexicalEntries con lessico vuoto

### ISSUE THREAD

**Issue by magoafono** [andreabellandi/LexO-backend#2]
23-Nov-2023 15:05:47.953 GRAVE [http-nio-8080-exec-59] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Jersey Servlet] in context with path [/LexO-backend-maia-complit] threw exception [java.lang.NullPointerException] with root cause
	java.lang.NullPointerException
		at it.cnr.ilc.lexo.service.helper.TripleStoreDataHelper.newDataList(TripleStoreDataHelper.java:43)
		at it.cnr.ilc.lexo.service.LexiconData.entriesList(LexiconData.java:579)

**Comment by andreabellandi** [comment]
It should be fixed. Please, verify.

Cheers,
Andrea
